---
# tasks file for ansible.ddclient
- name: Gathering OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: 'true'
  tags: ['ddclient']

- include: install.yml
  tags: ['ddclient']

- include: configure.yml
  tags: ['ddclient']
